language: node_js

node_js:
  - "6.2.0"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - develop
    - master

after_script:
  - cat ./coverage/lcov.info | coveralls
  - npm run post-build

