language: node_js

node_js:
  - "6.2.0"

services: mongodb

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - develop
    - master

after_script:
  - cat ./coverage/lcov.info | coveralls
  - npm run post-build

